version: "3.9"
services:
  api:
    build: 
      dockerfile: Dockerfile
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: mysecretpassword
      DATABASE_NAME: postgres
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres

    
