version: "3.9"
services:
  api:
    build: 
      dockerfile: Dockerfile
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_DATABASE: postgres
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres

    
