apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: my-app  
  template:
    metadata:
      labels:
        app: my-app  
    spec:
      containers:
        - name: group2-container 
          image: <ECR_REPOSITORY_URL>:<TAG>  # Replace with the ECR repository URL and image tag
          ports:
            - containerPort: 80  # Port exposed by the container
          env:
            - name: ENV_VAR_NAME  # Environment variable name
              value: ENV_VAR_VALUE  # Environment variable value