apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: app
          image: 129392916120.dkr.ecr.eu-north-1.amazonaws.com/group2-ecr:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              value: group2-db.cjsnrrorjfz7.eu-north-1.rds.amazonaws.com
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              value: postgres
            - name: DATABASE_NAME
              value: dev
          imagePullPolicy: Always